name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build MockHttpServer.UnitTests/MockHttpServer.UnitTests.csproj
      - name: Test
        run: dotnet test MockHttpServer.UnitTests/MockHttpServer.UnitTests.csproj
